# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  max_bump:
    description: maximum version to bump. Valid values are MAJOR, MINOR and PATCH
    required: true
    default: MAJOR
  min_bump:
    description: maximum version to bump. Valid values are MAJOR, MINOR and PATCH
    required: true
    default: PATCH
  token:
    description: 'a token...for github'
    default: ${{ github.token }}
    required: true
outputs:
  next_version:
    description: 'the result of semver-next'
runs:
  using: 'docker'
  image: 'Dockerfile'

